const supabase = require("../config/supabaseClient");
const crypto = require("crypto");

// ─────────────────────────────────────────────────────────
// GENERATE UNIQUE RECEIPT ID
// Format: AIT-RCT-XXXX-XXXX
// ─────────────────────────────────────────────────────────
function generateReceiptId() {
  const hex = crypto.randomBytes(4).toString("hex").toUpperCase();
  return `AIT-RCT-${hex.slice(0, 4)}-${hex.slice(4)}`;
}

// ─────────────────────────────────────────────────────────
// BUILD RECEIPT DATA
// Fetches all info needed for the receipt from DB
// ─────────────────────────────────────────────────────────
async function buildReceiptData(paymentId) {
  // Fetch payment with member and committee info
  const { data: payment, error } = await supabase
    .from("payment_records")
    .select(`
      *,
      members(id, name, phone, committee_id),
      committees(id, name, monthly_amount, organizer_id)
    `)
    .eq("id", paymentId)
    .single();

  if (error || !payment) {
    throw new Error("Payment not found for receipt generation");
  }

  // Fetch trust score
  const { data: trustScore } = await supabase
    .from("trust_scores")
    .select("score")
    .eq("member_id", payment.member_id)
    .eq("committee_id", payment.committee_id)
    .maybeSingle();

  // Count total confirmed payments for this member in this committee
  const { count: totalConfirmed } = await supabase
    .from("payment_records")
    .select("*", { count: "exact", head: true })
    .eq("member_id", payment.member_id)
    .eq("committee_id", payment.committee_id)
    .eq("status", "confirmed");

  // Get committee member count for total contribution context
  const { count: memberCount } = await supabase
    .from("members")
    .select("*", { count: "exact", head: true })
    .eq("committee_id", payment.committee_id);

  const receiptId = generateReceiptId();
  const now = new Date();
  const verificationDate = now.toLocaleDateString("en-PK", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const verificationTime = now.toLocaleTimeString("en-PK", {
    hour: "2-digit",
    minute: "2-digit",
  });

  return {
    receiptId,
    memberName: payment.members?.name || "Member",
    memberPhone: payment.members?.phone || "",
    committeeName: payment.committees?.name || "Committee",
    monthlyAmount: payment.amount || payment.committees?.monthly_amount || 0,
    month: payment.month || "N/A",
    paymentDate: payment.created_at
      ? new Date(payment.created_at).toLocaleDateString("en-PK", {
          day: "numeric",
          month: "long",
          year: "numeric",
        })
      : "N/A",
    verificationDate,
    verificationTime,
    verificationStatus: "Confirmed ✓",
    trustScore: trustScore?.score ?? 50,
    totalConfirmedPayments: totalConfirmed || 0,
    totalMembers: memberCount || 0,
    paymentId: payment.id,
  };
}

// ─────────────────────────────────────────────────────────
// FORMAT FOR WHATSAPP (text-based receipt)
// ─────────────────────────────────────────────────────────
function formatForWhatsApp(receipt) {
  const stars = "⭐".repeat(Math.min(5, Math.ceil(receipt.trustScore / 20)));

  return (
    ` *PAYMENT RECEIPT BY AITBAAR*\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━\n\n` +
    ` *Receipt ID:* ${receipt.receiptId}\n` +
    ` *Member:* ${receipt.memberName}\n` +
    ` *Committee:* ${receipt.committeeName}\n` +
    ` *Month:* ${receipt.month}\n\n` +
    ` *Amount Paid:* Rs ${receipt.monthlyAmount.toLocaleString()}\n` +
    ` *Payment Date:* ${receipt.paymentDate}\n` +
    ` *Status:* ${receipt.verificationStatus}\n\n` +
    ` *Your Stats:*\n` +
           +
    `   🔹 Total Confirmed: ${receipt.totalConfirmedPayments} payments\n` +
           +
    ` *Verified on:* ${receipt.verificationDate} at ${receipt.verificationTime}\n` +
    `━━━━━━━━━━━━━━━━━━━━━━━━━\n` +
    `_This receipt is digitally generated by Aitbaar._\n` +
    `_For disputes, contact your committee organizer._`
  );
}

// ─────────────────────────────────────────────────────────
// GENERATE HTML RECEIPT (for dashboard download/print)
// ─────────────────────────────────────────────────────────
function generateReceiptHtml(receipt) {
  const trustColor =
    receipt.trustScore >= 80
      ? "#16A34A"
      : receipt.trustScore >= 50
        ? "#D97706"
        : "#DC2626";

  const trustLabel =
    receipt.trustScore >= 80
      ? "Excellent"
      : receipt.trustScore >= 60
        ? "Good"
        : receipt.trustScore >= 40
          ? "Fair"
          : "Needs Improvement";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Payment Receipt — ${receipt.receiptId}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #F7F6F2; display: flex; justify-content: center; padding: 30px; }
    .receipt { background: #fff; border-radius: 16px; max-width: 420px; width: 100%; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.08); }
    .receipt-header { background: linear-gradient(135deg, #1E3A5F 0%, #2E5384 100%); color: white; padding: 24px; text-align: center; }
    .receipt-header h1 { font-size: 18px; font-weight: 700; margin-bottom: 4px; letter-spacing: 0.5px; }
    .receipt-header .subtitle { font-size: 11px; opacity: 0.8; }
    .receipt-id { background: #FBF0DE; color: #B8792B; font-size: 13px; font-weight: 700; padding: 8px 16px; text-align: center; letter-spacing: 1px; }
    .receipt-body { padding: 20px 24px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-bottom: 18px; }
    .info-item { }
    .info-label { font-size: 10px; color: #5C6270; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 2px; }
    .info-value { font-size: 13px; color: #22262E; font-weight: 600; }
    .amount-section { background: #F0F7FF; border-radius: 10px; padding: 14px 16px; text-align: center; margin-bottom: 18px; }
    .amount-label { font-size: 10px; color: #5C6270; text-transform: uppercase; letter-spacing: 0.5px; }
    .amount-value { font-size: 28px; font-weight: 800; color: #1E3A5F; margin-top: 2px; }
    .status-badge { display: inline-block; background: #ECFDF5; color: #16A34A; font-size: 12px; font-weight: 600; padding: 4px 12px; border-radius: 20px; border: 1px solid #BBF7D0; }
    .stats-section { border-top: 1px dashed #E8EEF4; padding-top: 14px; margin-top: 4px; }
    .stats-row { display: flex; justify-content: space-between; align-items: center; padding: 6px 0; }
    .stats-label { font-size: 12px; color: #5C6270; }
    .stats-value { font-size: 12px; font-weight: 600; color: #22262E; }
    .trust-bar { width: 100%; height: 6px; background: #E8EEF4; border-radius: 3px; margin-top: 6px; overflow: hidden; }
    .trust-fill { height: 100%; border-radius: 3px; transition: width 0.3s; }
    .trust-info { display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px; }
    .trust-label { font-size: 12px; font-weight: 600; }
    .receipt-footer { background: #F7F6F2; padding: 14px 24px; text-align: center; border-top: 1px solid #E8EEF4; }
    .receipt-footer p { font-size: 10px; color: #5C6270; line-height: 1.5; }
    .qr-placeholder { font-size: 10px; color: #B8792B; margin-top: 6px; font-weight: 600; }
    @media print { body { background: white; padding: 0; } .receipt { box-shadow: none; border: 1px solid #E8EEF4; } }
  </style>
</head>
<body>
  <div class="receipt">
    <!-- Header -->
    <div class="receipt-header">
      <h1>AITBAAR</h1>
      <div class="subtitle">Digital Payment Receipt</div>
    </div>

    <!-- Receipt ID -->
    <div class="receipt-id">${receipt.receiptId}</div>

    <!-- Body -->
    <div class="receipt-body">
      <!-- Info Grid -->
      <div class="info-grid">
        <div class="info-item">
          <div class="info-label">Member</div>
          <div class="info-value">${receipt.memberName}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Committee</div>
          <div class="info-value">${receipt.committeeName}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Month / Cycle</div>
          <div class="info-value">${receipt.month}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Payment Date</div>
          <div class="info-value">${receipt.paymentDate}</div>
        </div>
      </div>

      <!-- Amount -->
      <div class="amount-section">
        <div class="amount-label">Amount Paid</div>
        <div class="amount-value">Rs ${receipt.monthlyAmount.toLocaleString()}</div>
        <div style="margin-top: 6px;">
          <span class="status-badge">✅ ${receipt.verificationStatus}</span>
        </div>
      </div>

      <!-- Stats -->
      <div class="stats-section">
        <div class="trust-info">
          <span class="trust-label" style="color: ${trustColor};">Trust Score: ${receipt.trustScore}/100</span>
          <span style="font-size: 11px; color: #5C6270;">${trustLabel}</span>
        </div>
        <div class="trust-bar">
          <div class="trust-fill" style="width: ${receipt.trustScore}%; background: ${trustColor};"></div>
        </div>

        <div class="stats-row" style="margin-top: 10px;">
          <span class="stats-label">Total Confirmed Payments</span>
          <span class="stats-value">${receipt.totalConfirmedPayments}</span>
        </div>
        <div class="stats-row">
          <span class="stats-label">Committee Size</span>
          <span class="stats-value">${receipt.totalMembers} members</span>
        </div>
        <div class="stats-row">
          <span class="stats-label">Verified On</span>
          <span class="stats-value">${receipt.verificationDate} ${receipt.verificationTime}</span>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="receipt-footer">
      <p>This receipt is digitally generated by Aitbaar.<br>For disputes, contact your committee organizer.</p>
      <div class="qr-placeholder">ID: ${receipt.receiptId}</div>
    </div>
  </div>
</body>
</html>`;
}

module.exports = {
  buildReceiptData,
  formatForWhatsApp,
  generateReceiptHtml,
  generateReceiptId,
};