   import "./phoneMockup.css";

export default function PhoneMockup() {
  return (
    <div className="phone-mockup">
      <div className="phone-screen">
        {/* Dynamic island */}
        <div className="phone-notch" />

        {/* Status bar */}
        <div className="phone-status-bar">
          <span>10:30</span>
          <span className="phone-status-icons">
            <span>ıll</span>
            <span>▲</span>
            <span className="phone-battery" />
          </span>
        </div>

        {/* Header */}
        <div className="phone-header">
          <div className="phone-header-left">
            <span className="phone-back">←</span>
            <div className="phone-avatar" />
            <div className="phone-header-text">
              <p className="phone-title">Aitbaar AI</p>
              <span className="phone-online">online</span>
            </div>
          </div>
          <div className="phone-header-right">
            <span className="phone-header-icon">📹</span>
            <span className="phone-header-icon">📞</span>
            <span className="phone-header-menu">⋮</span>
          </div>
        </div>

        {/* Chat */}
        <div className="phone-chat">
          <span className="phone-date-chip">Today</span>

          {/* Voice note */}
          <div className="phone-voice">
            <div className="phone-voice-icon">🎤</div>
            <div className="phone-voice-body">
              <p className="phone-voice-label">Voice Note</p>
              <div className="phone-voice-player">
                <span className="phone-voice-play">▶</span>
                <div className="phone-voice-wave">
                  <span className="phone-voice-knob" />
                </div>
              </div>
              <div className="phone-voice-meta">
                <span>0:12</span>
                <span className="phone-voice-time">
                  10:30 AM <span className="phone-read-check">✓✓</span>
                </span>
              </div>
            </div>
          </div>

          {/* Received message */}
          <div className="phone-message">
            <p className="phone-message-text">
              Payment of Rs 20,000 has been recorded.
            </p>
            <span className="phone-message-time">10:31 AM</span>
          </div>

          {/* Payment receipt card — compact */}
          <div className="phone-receipt-card">
            <div className="phone-receipt-header">
              <p className="phone-receipt-brand">AITBAAR</p>
              <p className="phone-receipt-subtitle">Digital Payment Receipt</p>
            </div>
            <div className="phone-receipt-id-bar">AIT-RCT-1A39-6ABD</div>
            <div className="phone-receipt-body">
              <div className="phone-receipt-grid">
                <div>
                  <p className="phone-receipt-label">MEMBER</p>
                  <p className="phone-receipt-value">Samar Naaz</p>
                </div>
                <div>
                  <p className="phone-receipt-label">COMMITTEE</p>
                  <p className="phone-receipt-value">kamaiti</p>
                </div>
                <div>
                  <p className="phone-receipt-label">MONTH</p>
                  <p className="phone-receipt-value">Sept 2026</p>
                </div>
                <div>
                  <p className="phone-receipt-label">DATE</p>
                  <p className="phone-receipt-value">2 Sept 2026</p>
                </div>
              </div>
              <div className="phone-receipt-amount-box">
                <p className="phone-receipt-amount-label">AMOUNT PAID</p>
                <p className="phone-receipt-amount">Rs 20,000</p>
                <span className="phone-receipt-badge">✅ Confirmed ✓</span>
              </div>
              <div className="phone-receipt-trust">
                <span className="phone-receipt-trust-text">Trust Score: 100/100</span>
                <span className="phone-receipt-trust-label">Excellent</span>
              </div>
              <div className="phone-receipt-bar-track">
                <div className="phone-receipt-bar-fill" />
              </div>
              <div className="phone-receipt-stats">
                <p>Total Confirmed: 2 payments · Committee: 7 members</p>
              </div>
            </div>
            <div className="phone-receipt-footer">
              <p>Digitally generated by Aitbaar · ID: AIT-RCT-1A39-6ABD <span> 10:31 AM</span></p>
            </div>
          </div>
          {/* <span className="phone-trust-time" style={{alignSelf: "flex-end"}}>10:31 AM</span> */}
        </div>

        {/* Input */}
        <div className="phone-input-row">
          <div className="phone-input">
            <span className="phone-input-emoji">😊</span>
            <span className="phone-input-placeholder">Type a message</span>
            <span className="phone-input-attach">📎</span>
            <span className="phone-input-camera">📷</span>
          </div>
          <div className="phone-mic">🎤</div>
        </div>

        {/* Home indicator */}
        <div className="phone-home-indicator" />
      </div>
    </div>
  );
}